### ISSUE TITLE
Add config parameter for particle fade out

### ISSUE THREAD

**Issue by Tscheffrey** [daniel-lundin/dom-confetti#10]
A parameter that controls how fast the particles will fade out once launched.

Currently, you can only control the decay of the explosion movement, not the visibility.

Great project btw!

**Comment by daniel-lundin** [comment]
Thanks!

Yes that would be nice, right now it's hardcoded to 200 ticks(requestAnimationFrames) but that could be exposed as a parameter.

Don't have time in a while, but if you've got time PRs are welcome :)

**Comment by inorganik** [comment]
I agree this would be a great thing to add. I am loving this lib! I looked at a bunch and this one was the best imho. I made an angular directive for it. 

One other suggestion - extend default options with passed in options rather than completely replacing them. That way you could just override 1 property without having to set all of them.

**Comment by daniel-lundin** [comment]
Cool! Is the angular directive published to npm so I can link to it? I'm sure there would be some interest.
I've fixed and published the second one where default options are extended instead of replaced.

**Comment by inorganik** [comment]
Packaging up Angular directives/components is kind of a pain, but here is a gist: 

https://gist.github.com/inorganik/f20c78943308a7124c830c02adc7b1b2

**Comment by daniel-lundin** [comment]
I added an additional parameter `duration` that will control the length of the fade out.
Available in version 0.0.15.
